# Generated by Django 3.2.19 on 2023-05-17 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='django_user_ref',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='app_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
