# Generated by Django 3.2.19 on 2023-05-18 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20230517_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='location',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='appuser',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
