# Generated by Django 3.2.19 on 2023-06-04 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20230604_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='image',
            field=models.ImageField(blank=True, upload_to='users/%Y/%m/%d/'),
        ),
    ]
